### ISSUE TITLE
KeyError: 'r'

### ISSUE THREAD

**Issue by xtalker** [evilpete/ISYlib-python#18]
I've seen this error twice now?  Not sure what triggers it.

``
Exception in thread event_looper:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ISY/IsyEvent.py", line 594, in events_loop
    self.process_func(d, self.process_func_arg, x)
  File "/usr/local/lib/python2.7/dist-packages/ISY/IsyClass.py", line 501, in _read_event
    prog_dict['lastRunTime'] = evnt_dat['eventInfo']['r']
KeyError: 'r'
``

My program is simply checking an ISY var:
``
driveway_flag = myisy.get_var("Driveway_Flag")
``

**Comment by xtalker** [comment]
This happens with Python 2.7.3 on a RasPi2.  

I must be the only one seeing this?  Any input appreciated!

**Comment by evilpete** [comment]
Fixed in latest merge with dev branch
