### ISSUE TITLE
variable reads don't update

### ISSUE THREAD

**Issue by stevenmcastano** [evilpete/ISYlib-python#19]
I've been working with the library and so far everything seems great, but one problem I've found is that variable values don't update.

I have my code set like this:

```
while True:
    isy_VARIABLE_NAME = isy.get_var("VARIABLE_NAME")
    value = isy_VARIABLE_NAME.get_var_value()
    logger.debug("The current value of WD_EventGhost: {}".format(value))
    time.sleep(60)
```

The first time the look runs it's perfect, it grabs the value of the variable named "VARIABLE_NAME", but then after I update the value on the ISY, it never updates what python sees. Also as if it's only reaching out the ISY once.

However, if I use:
```
counter = 0
while True:
    isy_VARIABLE_NAME.value = counter
    counter = counter + 1
    time.sleep(60)
```
it updates the variable without problems

Any ideas?

**Comment by evilpete** [comment]
Are you creating the ISY class with the option eventupdates=1

Eg:

myisy = ISY.Isy(addr="10.1.1.3", eventupdates=1)

**Comment by stevenmcastano** [comment]
I hadn't been no, but I just added it in and that looks like it's working great! Thanks!

**Comment by evilpete** [comment]
That option causes a sub thread to be created that reads events from the
ISY  device and updates object states & values

**Comment by stevenmcastano** [comment]
I'm seeing that yeah, a bunch of extra screen output comes out when the isy object is created now. My test tool worked... and it the first test of a single variable is working on a single cycle in my app code, I should have it tested for multiple variables with multiple updates in a few threads shortly. The test is running now.

**Comment by stevenmcastano** [comment]
Looks like there's an odd error coming from the event updates. This just popped up when a program on the ISY updated another varible... one I'm not even using in my code:

```
Exception in thread event_looper:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ISY/IsyEvent.py", line 597, in events_loop
    self.process_func(d, self.process_func_arg, x)
  File "/usr/local/lib/python2.7/dist-packages/ISY/IsyClass.py", line 501, in _read_event
    prog_dict['lastRunTime'] = evnt_dat['eventInfo']['r']
KeyError: 'r'
```
The question now is, will this disturb the thread monitoring updates and stop catching them? Or is the thread still running?

**Comment by stevenmcastano** [comment]
And yes, from my testing is does look like the background thread is dead and not getting updates anymore. I updated my variable on the ISY and it's not being read in the ".value" statement anymore.

**Comment by evilpete** [comment]
What software version is your ISY?  If you're running 5.x make sure you are
running the version from GitHub.  There are some changes to the  event XML
data  format that I recently added work around for ( it's not fully tested
for backwards compatibility thus not pushec to the PyPi repository yet )

**Comment by stevenmcastano** [comment]
I'm in version 4.5.1
